export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const SETLOADING = "SETLOADING";
export const LOGOUT = "LOGOUT";
export const GETAUTHUSER = "GETAUTHUSER";
